steps:
# Install gox
- name: 'golang'
  args: ['go', 'install', 'github.com/mitchellh/gox@latest']
# Build binaries for target OS list
- name: 'golang'
  entrypoint: gox
  args: ['-os="linux darwin windows"', '-arch="amd64"', '-output="./dist/pluralith-cli_v0.0.1_{{.OS}}_{{.Arch}}"']
  dir: 'app'
- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./dist", "gs://pluralith-cli-releases"]
options:
  volumes:
  - name: 'go-modules'
    path: /go