project_name: pluralith

gomod:
  proxy: true

builds:
  - env:
      - CGO_ENABLED=0
    main: ./
    binary: pluralith
    ldflags:
      - -s -w
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    replacements:
    files:
      - LICENSE
      - README.md
      - doc/tutorial/**/*
      - doc/ref/spec.md
    format_overrides:
      - goos: windows
        format: zip

release:
  disable: true
  prerelease: auto

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^test:"

brews:
  - tap:
      owner: Pluralith
      name: pluralith-homebrew-tap
    commit_author:
      name: Daniel Putzer
      email: danielputzer.work@gmail.com
    homepage: "https://www.pluralith.com"
    description: "Pluralith is an application to visualize your Terraform state and document your infrastructure in an automated way"
    test: |
      system "#{bin}/pluralith version"
